# Generated by Django 5.1.1 on 2024-09-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='upload_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
